/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#dad7ff",
        "surface-container-highest": "#e4e1ee",
        "surface": "#fcf8ff",
        "secondary-fixed-dim": "#b7c8e1",
        "surface-bright": "#fcf8ff",
        "inverse-primary": "#c3c0ff",
        "on-secondary-fixed-variant": "#38485d",
        "surface-dim": "#dcd8e5",
        "secondary-container": "#d0e1fb",
        "secondary": "#505f76",
        "tertiary-fixed-dim": "#ffb695",
        "on-surface": "#1b1b24",
        "on-error-container": "#93000a",
        "tertiary-container": "#a44100",
        "outline-variant": "#c7c4d8",
        "surface-container": "#f0ecf9",
        "on-tertiary-fixed": "#351000",
        "surface-tint": "#4d44e3",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#e2dfff",
        "on-surface-variant": "#464555",
        "background": "#fcf8ff",
        "on-tertiary-container": "#ffd2be",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#7b2f00",
        "primary-fixed-dim": "#c3c0ff",
        "on-secondary": "#ffffff",
        "primary-container": "#4f46e5",
        "inverse-surface": "#302f39",
        "on-background": "#1b1b24",
        "surface-variant": "#e4e1ee",
        "tertiary-fixed": "#ffdbcc",
        "surface-container-high": "#eae6f4",
        "on-secondary-fixed": "#0b1c30",
        "error-container": "#ffdad6",
        "tertiary": "#7e3000",
        "on-secondary-container": "#54647a",
        "inverse-on-surface": "#f3effc",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-low": "#f5f2ff",
        "primary": "#3525cd",
        "on-primary-fixed": "#0f0069",
        "secondary-fixed": "#d3e4fe",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#3323cc",
        "outline": "#777587",
        slate: { 50: "#f8fafc", 100: "#f1f5f9", 200: "#e2e8f0", 500: "#64748b", 900: "#0f172a" },
        indigo: { 50: "#eef2ff", 100: "#e0e7ff", 600: "#4f46e5", 700: "#4338ca" }
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", "2xl": "1rem", full: "9999px" },
      spacing: {
        "stack-lg": "24px",
        "sidebar-width": "250px",
        "gutter": "24px",
        "stack-md": "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "stack-sm": "8px",
        "container-max-width": "1440px"
      },
      fontFamily: { 
        "body-lg": ["Inter", "sans-serif"], 
        "headline-lg": ["Inter", "sans-serif"], 
        "body-md": ["Inter", "sans-serif"], 
        "label-md": ["Inter", "sans-serif"], 
        "headline-xl": ["Inter", "sans-serif"], 
        "headline-md": ["Inter", "sans-serif"] 
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
